[sequences]
# Format: <sequenceName>=<position1>:<action1>:<position2>:<position3>
# Reads like: Go to position 1, then complete action 1, then go to position 2, lastly go to position 3
# Sequence can have 1:n postions and/or actions and can be in any order.  Will complete each one left to right.
WeldDrone=Phase1:Step1:WelderOn:Step2:Step3:Step4:Step5:Step6:Step7:Step8:Step9:Step10:Step11:Phase2:Step12:Step13:Step14a:Step14b:Step15:Step16:Step17:Step18:Step19:Step20:Step21:FinalPhase:Step22:Step23:Step24:Step25:WelderOff:Stowed

# Actions and Positions
# Format: 
# [ActionName]
# <BlockName>:<BlockType>:<TakeAction>

[Phase1]
Printer - Projector - Phase 1:Projector:True
Printer - Projector - Phase 2:Projector:False
Printer - Projector - Final Phase:Projector:False

[Phase2]
Printer - Projector - Phase 1:Projector:False
Printer - Projector - Phase 2:Projector:True
Printer - Projector - Final Phase:Projector:False

[FinalPhase]
Printer - Projector - Phase 1:Projector:False
Printer - Projector - Phase 2:Projector:False
Printer - Projector - Final Phase:Projector:True

[WelderOn]
Printer - LA - Welder:Welder:True
Printer - RA - Welder:Welder:True
Printer - Alert Light 1:Light:True
Printer - Alert Light 2:Light:True

[WelderOff]
Printer - LA - Welder:Welder:False
Printer - RA - Welder:Welder:False
Printer - Alert Light 1:Light:False
Printer - Alert Light 2:Light:False

# [PositionName]
# <BlockName>:<BlockType>:<MoveTo>:<Velocity>

[Stowed]
Printer - LA - Hinge 1:Hinge:90.0:1.0
Printer - LA - Hinge 2:Hinge:-90.0:1.0
Printer - LA - Hinge 3:Hinge:-90.0:1.0
Printer - LA - Rotor:Rotor:0.0:1.0
Printer - RA - Hinge 1:Hinge:90.0:1.0
Printer - RA - Hinge 2:Hinge:-90.0:1.0
Printer - RA - Hinge 3:Hinge:-90.0:1.0
Printer - RA - Rotor:Rotor:0.0:1.0
Printer - LA - Welder:Welder:False
Printer - RA - Welder:Welder:False
Printer - Projector - Phase 1:Projector:False
Printer - Projector - Phase 2:Projector:False
Printer - Projector - Final Phase:Projector:False

[Step1]
Printer - LA - Hinge 1:Hinge:57.0:0.579
Printer - LA - Hinge 2:Hinge:-35.0:0.965
Printer - LA - Hinge 3:Hinge:-66.0:0.421
Printer - LA - Rotor:Rotor:-33.0:1.0
Printer - RA - Hinge 1:Hinge:57.0:0.579
Printer - RA - Hinge 2:Hinge:-35.0:0.965
Printer - RA - Hinge 3:Hinge:-66.0:0.421
Printer - RA - Rotor:Rotor:33.0:1.0

[Step2]
Printer - LA - Hinge 1:Hinge:57.0:0.0
Printer - LA - Hinge 2:Hinge:-25.0:0.175
Printer - LA - Hinge 3:Hinge:-50.0:0.281
Printer - LA - Rotor:Rotor:-25.0:0.211
Printer - RA - Hinge 1:Hinge:57.0:0.0
Printer - RA - Hinge 2:Hinge:-25.0:0.175
Printer - RA - Hinge 3:Hinge:-50.0:0.281
Printer - RA - Rotor:Rotor:25.0:0.211

[Step3]
Printer - LA - Hinge 1:Hinge:57.0:0.0
Printer - LA - Hinge 2:Hinge:0.0:0.439
Printer - LA - Hinge 3:Hinge:-25.0:0.800
Printer - LA - Rotor:Rotor:2.0:0.404
Printer - RA - Hinge 1:Hinge:57.0:0.0
Printer - RA - Hinge 2:Hinge:0.0:0.439
Printer - RA - Hinge 3:Hinge:-25.0:0.800
Printer - RA - Rotor:Rotor:-2.0:0.404

[Step4]
Printer - LA - Hinge 1:Hinge:60.0:0.053
Printer - LA - Hinge 2:Hinge:0.0:0.0
Printer - LA - Hinge 3:Hinge:-42.0:0.298
Printer - LA - Rotor:Rotor:8.0:0.105
Printer - RA - Hinge 1:Hinge:60.0:0.053
Printer - RA - Hinge 2:Hinge:0.0:0.0
Printer - RA - Hinge 3:Hinge:-42.0:0.298
Printer - RA - Rotor:Rotor:-8.0:0.105

[Step5]
Printer - LA - Hinge 1:Hinge:45.0:0.263
Printer - LA - Hinge 2:Hinge:6.0:0.105
Printer - LA - Hinge 3:Hinge:-47.0:0.088
Printer - LA - Rotor:Rotor:8.0:0.0
Printer - RA - Hinge 1:Hinge:45.0:0.263
Printer - RA - Hinge 2:Hinge:6.0:0.105
Printer - RA - Hinge 3:Hinge:-47.0:0.088
Printer - RA - Rotor:Rotor:-8.0:0.0

[Step6]
Printer - LA - Hinge 1:Hinge:45.0:0.0
Printer - LA - Hinge 2:Hinge:10.0:0.070
Printer - LA - Hinge 3:Hinge:-64.0:0.298
Printer - LA - Rotor:Rotor:5.0:0.053
Printer - RA - Hinge 1:Hinge:45.0:0.0
Printer - RA - Hinge 2:Hinge:10.0:0.070
Printer - RA - Hinge 3:Hinge:-64.0:0.298
Printer - RA - Rotor:Rotor:-5.0:0.053

[Step7]
Printer - LA - Hinge 1:Hinge:32.0:0.228
Printer - LA - Hinge 2:Hinge:10.0:0.0
Printer - LA - Hinge 3:Hinge:-64.0:0.0
Printer - LA - Rotor:Rotor:6.0:0.018
Printer - RA - Hinge 1:Hinge:32.0:0.228
Printer - RA - Hinge 2:Hinge:10.0:0.0
Printer - RA - Hinge 3:Hinge:-64.0:0.0
Printer - RA - Rotor:Rotor:-6.0:0.018

[Step8]
Printer - LA - Hinge 1:Hinge:14.0:0.316
Printer - LA - Hinge 2:Hinge:-10.0:0.150
Printer - LA - Hinge 3:Hinge:-64.0:0.0
Printer - LA - Rotor:Rotor:6.0:0.0
Printer - RA - Hinge 1:Hinge:14.0:0.316
Printer - RA - Hinge 2:Hinge:-10.0:0.150
Printer - RA - Hinge 3:Hinge:-64.0:0.0
Printer - RA - Rotor:Rotor:-6.0:0.0

[Step9]
Printer - LA - Hinge 1:Hinge:14.0:0.0
Printer - LA - Hinge 2:Hinge:-16.0:0.105
Printer - LA - Hinge 3:Hinge:-64.0:0.0
Printer - LA - Rotor:Rotor:-13.0:0.333
Printer - RA - Hinge 1:Hinge:14.0:0.0
Printer - RA - Hinge 2:Hinge:-16.0:0.105
Printer - RA - Hinge 3:Hinge:-64.0:0.0
Printer - RA - Rotor:Rotor:13.0:0.333

[Step10]
Printer - LA - Hinge 1:Hinge:25.0:0.05
Printer - LA - Hinge 2:Hinge:-35.0:0.750
Printer - LA - Hinge 3:Hinge:-60.0:0.070
Printer - LA - Rotor:Rotor:-37.0:0.421
Printer - RA - Hinge 1:Hinge:25.0:0.05
Printer - RA - Hinge 2:Hinge:-35.0:0.750
Printer - RA - Hinge 3:Hinge:-60.0:0.070
Printer - RA - Rotor:Rotor:37.0:0.421

[Step11]
Printer - LA - Hinge 1:Hinge:45.0:0.351
Printer - LA - Hinge 2:Hinge:-42.0:0.123
Printer - LA - Hinge 3:Hinge:-75.0:0.263
Printer - LA - Rotor:Rotor:-51.0:0.246
Printer - RA - Hinge 1:Hinge:45.0:0.351
Printer - RA - Hinge 2:Hinge:-42.0:0.123
Printer - RA - Hinge 3:Hinge:-75.0:0.263
Printer - RA - Rotor:Rotor:51.0:0.246

[Step12]
Printer - LA - Hinge 1:Hinge:69.0:0.263
Printer - LA - Hinge 2:Hinge:-45.0:0.053
Printer - LA - Hinge 3:Hinge:-89.0:0.246
Printer - LA - Rotor:Rotor:-58.0:0.123
Printer - RA - Hinge 1:Hinge:69.0:0.263
Printer - RA - Hinge 2:Hinge:-45.0:0.053
Printer - RA - Hinge 3:Hinge:-89.0:0.246
Printer - RA - Rotor:Rotor:58.0:0.123

[Step13]
Printer - LA - Hinge 1:Hinge:75.0:0.105
Printer - LA - Hinge 2:Hinge:-16.0:0.509
Printer - LA - Hinge 3:Hinge:-73.0:0.281
Printer - LA - Rotor:Rotor:-10.0:1.193
Printer - RA - Hinge 1:Hinge:75.0:0.105
Printer - RA - Hinge 2:Hinge:-16.0:0.509
Printer - RA - Hinge 3:Hinge:-73.0:0.281
Printer - RA - Rotor:Rotor:10.0:1.193

[Step14a]
Printer - LA - Hinge 1:Hinge:75.0:0.614
Printer - LA - Hinge 2:Hinge:-17.0:0.018
Printer - LA - Hinge 3:Hinge:-20.0:1.018
Printer - LA - Rotor:Rotor:0.0:0.175
Printer - RA - Hinge 1:Hinge:75.0:0.614
Printer - RA - Hinge 2:Hinge:-17.0:0.018
Printer - RA - Hinge 3:Hinge:-20.0:1.018

[Step14b]
Printer - LA - Hinge 1:Hinge:40.0:0.614
Printer - LA - Hinge 2:Hinge:-17.0:0.018
Printer - LA - Hinge 3:Hinge:0.0:1.018
Printer - LA - Rotor:Rotor:0.0:0.175
Printer - RA - Hinge 1:Hinge:40.0:0.614
Printer - RA - Hinge 2:Hinge:-17.0:0.018
Printer - RA - Hinge 3:Hinge:0.0:1.018
Printer - RA - Rotor:Rotor:0.0:0.175

[Step15]
Printer - LA - Hinge 1:Hinge:40.0:0.0
Printer - LA - Hinge 2:Hinge:15.0:0.561
Printer - LA - Hinge 3:Hinge:0.0:0.0
Printer - LA - Rotor:Rotor:0.0:0.0
Printer - RA - Hinge 1:Hinge:40.0:0.0
Printer - RA - Hinge 2:Hinge:15.0:0.561
Printer - RA - Hinge 3:Hinge:0.0:0.0
Printer - RA - Rotor:Rotor:0.0:0.0

[Step16]
Printer - LA - Hinge 1:Hinge:40.0:0.0
Printer - LA - Hinge 2:Hinge:15.0:0.0
Printer - LA - Hinge 3:Hinge:-36.0:0.632
Printer - LA - Rotor:Rotor:6.0:0.105
Printer - RA - Hinge 1:Hinge:40.0:0.0
Printer - RA - Hinge 2:Hinge:15.0:0.0
Printer - RA - Hinge 3:Hinge:-36.0:0.632
Printer - RA - Rotor:Rotor:-6.0:0.105

[Step17]
Printer - LA - Hinge 1:Hinge:40.0:0.0
Printer - LA - Hinge 2:Hinge:15.0:0.0
Printer - LA - Hinge 3:Hinge:-67.0:0.544
Printer - LA - Rotor:Rotor:15.0:0.158
Printer - RA - Hinge 1:Hinge:40.0:0.0
Printer - RA - Hinge 2:Hinge:15.0:0.0
Printer - RA - Hinge 3:Hinge:-67.0:0.544
Printer - RA - Rotor:Rotor:-15.0:0.158

[Step18]
Printer - LA - Hinge 1:Hinge:23.0:0.298
Printer - LA - Hinge 2:Hinge:20.0:0.088
Printer - LA - Hinge 3:Hinge:-67.0:0.0
Printer - LA - Rotor:Rotor:15.0:0.0
Printer - RA - Hinge 1:Hinge:23.0:0.298
Printer - RA - Hinge 2:Hinge:20.0:0.088
Printer - RA - Hinge 3:Hinge:-67.0:0.0
Printer - RA - Rotor:Rotor:-15.0:0.0

[Step19]
Printer - LA - Hinge 1:Hinge:-55.0:1.368
Printer - LA - Hinge 2:Hinge:9.0:0.192
Printer - LA - Hinge 3:Hinge:55.0:2.0
Printer - LA - Rotor:Rotor:0.0:0.263
Printer - RA - Hinge 1:Hinge:-55.0:1.368
Printer - RA - Hinge 2:Hinge:9.0:0.192
Printer - RA - Hinge 3:Hinge:55.0:2.0
Printer - RA - Rotor:Rotor:0.0:0.263

[Step20]
Printer - LA - Hinge 1:Hinge:-55.0:0.0
Printer - LA - Hinge 2:Hinge:-38.0:0.825
Printer - LA - Hinge 3:Hinge:45.0:0.175
Printer - LA - Rotor:Rotor:35.0:0.614
Printer - RA - Hinge 1:Hinge:-55.0:0.0
Printer - RA - Hinge 2:Hinge:-38.0:0.825
Printer - RA - Hinge 3:Hinge:45.0:0.175
Printer - RA - Rotor:Rotor:-35.0:0.614

[Step21]
Printer - LA - Hinge 1:Hinge:-55.0:0.0
Printer - LA - Hinge 2:Hinge:-50.0:0.211
Printer - LA - Hinge 3:Hinge:71.0:0.456
Printer - LA - Rotor:Rotor:43.0:0.140
Printer - RA - Hinge 1:Hinge:-55.0:0.0
Printer - RA - Hinge 2:Hinge:-50.0:0.211
Printer - RA - Hinge 3:Hinge:71.0:0.456
Printer - RA - Rotor:Rotor:-43.0:0.140

[Step22]
Printer - LA - Hinge 1:Hinge:-75.0:0.333
Printer - LA - Hinge 2:Hinge:-50.0:0.211
Printer - LA - Hinge 3:Hinge:71.0:0.456
Printer - LA - Rotor:Rotor:43.0:0.140
Printer - RA - Hinge 1:Hinge:-75.0:0.333
Printer - RA - Hinge 2:Hinge:-50.0:0.211
Printer - RA - Hinge 3:Hinge:71.0:0.456
Printer - RA - Rotor:Rotor:-43.0:0.140

[Step23]
Printer - LA - Hinge 1:Hinge:-75.0:0.0
Printer - LA - Hinge 2:Hinge:28.0:0.386
Printer - LA - Hinge 3:Hinge:71.0:0.456
Printer - LA - Rotor:Rotor:68.0:0.439
Printer - RA - Hinge 1:Hinge:-75.0:0.0
Printer - RA - Hinge 2:Hinge:28.0:0.386
Printer - RA - Hinge 3:Hinge:71.0:0.456
Printer - RA - Rotor:Rotor:-68.0:0.439

[Step24]
Printer - LA - Hinge 1:Hinge:-45.0:0.614
Printer - LA - Hinge 2:Hinge:28.0:0.0
Printer - LA - Hinge 3:Hinge:71.0:0.0
Printer - LA - Rotor:Rotor:68.0:0.0
Printer - RA - Hinge 1:Hinge:-45.0:0.614
Printer - RA - Hinge 2:Hinge:28.0:0.0
Printer - RA - Hinge 3:Hinge:71.0:1.0
Printer - RA - Rotor:Rotor:-68.0:0.0

[Step25]
Printer - LA - Hinge 1:Hinge:-45.0:0.614
Printer - LA - Hinge 2:Hinge:28.0:0.0
Printer - LA - Hinge 3:Hinge:25.0:1.684
Printer - LA - Rotor:Rotor:34.0:0.596
Printer - RA - Hinge 1:Hinge:-45.0:0.614
Printer - RA - Hinge 2:Hinge:28.0:0.0
Printer - RA - Hinge 3:Hinge:25.0:1.684
Printer - RA - Rotor:Rotor:-34.0:0.596